# syntax=docker/dockerfile:1

FROM golang:1.18-alpine AS base
EXPOSE $PORT

WORKDIR /app

RUN apk add build-base

COPY go.mod go.sum ./
RUN go mod download

COPY main.go  .
COPY pkgs/ pkgs/

CMD go run main.go