version: '3.3'

services:
  server:
    container_name: PROJECT_NAME
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
    ports:
      - 4000:4000
    env_file:
      - .env
